# Page settings

baseurl = "http://example.org/"
languageCode = "en-us"
title = "Brad Arnst"
theme = "orbit"
googleAnalytics = "UA-XXXXXXX-Y"

# Do not build files for websites. Need them? Set to false
disableRSS = true
disableSitemap = true
disable404 = true

[params]

# Meta
    description = "Brad Arnst Default CV"
    author = "Brad Arnst"

# Theme styles

    # The original template comes with 6 colour schemes. You may choose styles below.
    # "styles.css", "styles-2.css", "styles-3.css", "styles-4.css", "styles-5.css", "styles-6.css"
    # are available. Also the source LESS files are included so
    # it’s quick and easy to change the styling and colour scheme.

    styles = "styles.css"

# Sidebar sections

    # Profile section
    [params.profile]
        name = "Brad Arnst"
        tagline = "A Practical Architect"
        avatar = "profile.png"

    # Contact section
    [params.contact]
        enable = true

        [[params.contact.list]]
        class = "email"
        icon = "fa-envelope"
        url = "mailto: brad@nexusseven.com"
        title = "brad@nexusseven.com"

        [[params.contact.list]]
        class = "phone"
        icon = "fa-phone"
        url = "tel:+1234567890"
        title = "+1234567890"

        [[params.contact.list]]
        class = "website"
        icon = "fa-globe"
        url = "//cv.nexusseven.com.com"
        title = "cv.nexusseven.com"

        [[params.contact.list]]
        class = "linkedin"
        icon = "fa-linkedin"
        url = "//linkedin.com/in/bradarnst"
        title = "linkedin.com/in/bradarnst"

        [[params.contact.list]]
        class = "github"
        icon = "fa-github"
        url = "//github.com/bradarnst"
        title = "github.com/bradarnst"

        [[params.contact.list]]
        class = "twitter"
        icon = "fa-twitter"
        url = "//twitter.com/bradarnst"
        title = "@bradarnst"

    # Education section
    [params.education]
        enable = true
        title = "Education"

        [[params.education.list]]
        degree = " first year Computer Science"
        college = "Grande Prairie College"
        #dates = "2006 - 2010"

        [[params.education.list]]
        degree = "various technical and architecture training"
        college = "Microsoft, Oracle, f5"
        #dates = "2007 - 2011"

        [[params.education.list]]
        degree = "Delivering Exception Business Impact (Leadership Programme)"
        college = "fecund training"

    # Languages section
    [params.language]
        enable = true
        title = "Languages"

        [[params.language.list]]
        language = "English"
        level = "Native"

        [[params.language.list]]
        language = "French"
        level = "Starter"

    # Interests section
    [params.interests]
        enable = true
        title = "Interests"

        [[params.interests.list]]
        interest = "Mushroom Foraging"

        [[params.interests.list]]
        interest = "Travel"

        [[params.interests.list]]
        interest = "Cooking"

# Main body sections

    # You may use markdown in summary, details and intro fields. But don't overdose, it's resume!:)

    # Summary section
    [params.summary]
        enable = true
        icon = "fa-user"
        title = "My Profile"
        summary = "**Enterprise Technology Architect. Engineering / Technical Leader.**\n\nGuiding corporate strategies and technical direction; devising optimal architectures and designs;  directing digital transformation and integration; and leading teams to excellence.\n\nIs proficient in practical architecture, design, transformation and strategy. Leads, mentors, challenges, and collaborates with technical teams to produce their best results. Recognises opportunity and risk. Ensures current and future technology aligns with visions and goals. Broad and extensive experience: hands-on technical, senior team leadership, low-level design, enterprise architecture, project/waterfall, agile methodologies and ways of working, support, operations, management. Gives process and best practice its due, but always thinks outside the box. Experience in a variety of industries and products, using a variety of approaches, platforms, systems and frameworks. Experience in dealing with the issues and challenges facing startups, emerging companies and large, multi-national companies. Experience with global operations of corporations throughout North America, South America, Europe, and Asia-Pacific."
        #summary = "Is proficient in practical architecture, design, transformation and strategy. Leads, mentors, challenges, and collaborates with technical teams to produce their best results. Recognises opportunity and risk. Ensures current and future technology aligns with visions and goals. Broad and extensive experience: hands-on technical, senior team leadership, low-level design, enterprise architecture, project/waterfall, agile methodologies and ways of working, support, operations, management. Gives process and best practice its due, but always thinks outside the box. Experience in a variety of industries and products, using a variety of approaches, platforms, systems and frameworks. Experience in dealing with the issues and challenges facing startups, emerging companies and large, multi-national companies. Experience with global operations of corporations throughout North America, South America, Europe, and Asia-Pacific."

    # Experiences section
    [params.experiences]
        enable = true
        icon = "fa-briefcase"
        title = "Experiences"

        [[params.jobs.list]]
        position = "Enterprise Architect & Engineering Manager"
        dates = "Sept 2019 - Present"
        company = "Buildit @ Wipro Digital"
        details = "As **Enterprise Architect** responsible for consulting on architecture and strategy for clients and within Wipro Digital. Buildit is a leading, tip-of-the-spear team within Wipro Digital. Areas of responsibilities include: API strategy, digital transformation, enterprise integration, cloud strategy/architecture, DevOps, digital transformation, engineering transformation and agile ways of working.\n\nAs **Engineering Manager** responsible for mentoring Buildit and Wipro Digital engineering teams, consulting on engineering transformation with clients and within Wipro Digital. Introducing and refining ways of working, systems thinking, and a modern, digital approach.\n\n• architecture • manage • lead • AWS • Azure • strategy • Jira • devops • agile • scrum • API• REST • cloud • transformation • CI/CD pipeline  • UML • serverless • Docker • Kubernetes • JAMstack • git • consulting •"

        [[params.jobs.list]]
        position = "Principal Architect"
        dates = "Apr 2016 - Sep 2018"
        company = "Enterprise Blueprints"
        details = "As **Consulting Principal Architect**. Enterprise Blueprints provides Strategic and Architectural IT Consultation, primarily for financial organisations."

        [[params.jobs.list]]
        position = "Lead Enterprise Architect"
        dates = "Dec 2017 - Sep 2018"
        company = "10x (via Enterprise Blueprints)"
        details = "As **Lead Enterprise Architect** responsible for defining architectural concepts, and patterns for the 10x Platform and Virgin Money Digital Bank. Primary responsibilities include API strategy, API design, API management, integration within 10 and with external services and partners. 10x (with Virgin Money) was building a modern, bespoke digital banking platform using microservices architecture on AWS cloud native.\n\n• enterprise architecture • solutions architecture • design • integration architecture • microservices architecture • API design • API strategy • NoSQL data modelling • platform architecture • OpenAPI/Swagger • API security • Apigee Edge • Amazon AWS • OpenID/OAuth • UML • Spring Java microservices • linkerd service mesh •"

    # Projects section
    [params.projects]
        enable = true
        icon = "fa-archive"
        title = "Projects"
        intro = "**You can list your side projects or open source libraries in this section.** Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum et ligula in nunc bibendum fringilla a eu lectus"

        [[params.projects.list]]
        title = "Hugrid"
        url = "https://github.com/aerohub/hugrid"
        tagline = "Grid theme for Hugo. It's a kind of boilerplate to perform anyone or anything quickly. Portfolio, collection, bookmarks, contacts and so on"

    # Skills section
    [params.skills]
        enable = true
        icon = "fa-rocket"
        title = "Skills & Proficiency"

        [[params.skills.list]]
        skill = "Python & Django"
        level = "98%"
                
        [[params.skills.list]]
        skill = "Javascript & jQuery"
        level = "98%"

        [[params.skills.list]]
        skill = "Angular"
        level = "95%"

        [[params.skills.list]]
        skill = "HTML5 & CSS"
        level = "95%"

        [[params.skills.list]]
        skill = "Ruby on Rails"
        level = "75%"

        [[params.skills.list]]
        skill = "Sketch & Photoshop"
        level = "60%"

    # Footer section

    # The original template is released under the Creative Commons Attribution 3.0 License.
    # Please keep the original attribution link when using for your own project.
    # If you'd like to use the template without the attribution,
    # you can check out other license options via template author's website: themes.3rdwavemedia.com
    # 
    # As for Hugo port you may rewrite the "Ported for..." line with setting your name below.

    [params.footer]
        copyright = ""
